name: Validate terraform fmt
on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    name: terraform fmt check
    outputs:
      CHECK_STATUS: "${{ env.CHECK_STATUS }}"
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 20
      - name: Fetch changed files
        id: pr_files
        uses: Ana06/get-changed-files@v2.2.0
        with:
          format: 'space-delimited'
      - name: Configure terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.2
      - name: Validate terraform fmt
        run: |
          set +e

          echo "CHECK_STATUS=0" >> $GITHUB_ENV

          for changed_file in ${{ steps.pr_files.outputs.added_modified }}; do
            
            if [[ $changed_file == *.tf ]]; then
              echo -e "\e[1;36mChecking terraform fmt on ${changed_file}...\e[0m"
              terraform fmt -check $changed_file
              FMT_STATUS=$(echo $?)

              if [[ $FMT_STATUS -ne 0 ]]; then
                echo "❌ terraform fmt failed - ${changed_file}" >> $GITHUB_STEP_SUMMARY
                echo "CHECK_STATUS=1" >> $GITHUB_ENV
              else
                echo "✅ terraform fmt successful - ${changed_file}" >> $GITHUB_STEP_SUMMARY
              fi
            fi
          done
      - name: Process check
        if: always()
        run: exit $CHECK_STATUS
